### ISSUE TITLE
Still maintained?  Open for improvements?

### ISSUE THREAD

**Issue by paulharris** [smilingthax/cppcsv#1]
Hi,

I like the design of the CSV parser, seems the fastest and most complete out there (unless I haven't found THE better one yet).

I am wondering if you are active, and interesting in helping me extend it.
eg we could add quote-character auto detection, or at least be able to use set of possible quote-characters.
There are probably a couple of other things too.
I have a simple csv parser working already but its not as fast nor does it handle newlines or "" quoted quotes.

thanks,
Paul

**Comment by smilingthax** [comment]
Am 25.04.2013 03:10 schrieb "paulharris" notifications@github.com:

> I am wondering if you are active, and interesting in helping me extend it.

I have written cppcsv as component for one of my project, but did not have
time yet to use it there; I expect that I will do some additions (and
probaby fixes) to cppcsv in that process.

> eg we could add quote-character auto detection, or at least be able to
> use set of possible quote-characters.

I do want to have some way of quote+separator auto-detection, but I'm still
quite unsure how to best implement it / how the API should look like.
cppcsv's API is designed with the idea of potentially very large inputs
(many rows), and the idea of 'streaming' the data through.
For quote/separator auto-detection OTOH an API that gives guesses based on
a limited range/buffer would be more appropriate. Maybe it should also
return some measure of "certainty". Also it would probably test, which
separator/quote char of a certain (predefined?) set (i.e. one set of
possible quote-characters, and one set of separator-characters) works for a
certain input.

Parsing csv with a 'set of separators', where any one of it would act as
separator, leads to very unreliable results, IMO. Doing the same only for a
'set of quote characters' is not much better, and also complicates the
parsing state machine a lot.

Then there are also 'non-standard' ways to escape quote characters in csv.
The 'standard' way is to duplicate it, e.g.  "here "" is a quote". But
there are 'csv files' that e.g. use \". I'm not sure, whether cppcsv should
ever try to support those variants.

> There are probably a couple of other things too.
> I have a simple csv parser working already but its not as fast nor does
> it handle newlines or "" quoted quotes.

There is one known issue already on my TODO-list: Using multiple
invocations of operator() for one continuous input (stream, file, ...)
currently only works correctly when the boundaries are exactly at the end
of a csv row in the input.

  Tobias

**Comment by paulharris** [comment]
Hi Tobias,

I have forked your repo and have been working on it.  Check it out :)

Things to check (which covers some of your issues):
- Its now header-only, and in a namespace.  And I removed the extra C++11 stuff that wasn't necessary in the end (I simplified the static visitor and next() code).
- Better performance due to NO information kept in states or events.  ie the whitespace-buffer is reused so much less reallocs there.  All the states and events are now bare structs (ie tags) so can be passed around as copy (could/should be faster than by reference - no need for compiler to provide a memory address so they now compile out).
- Note also that the current character is not passed through the events anymore, and they do not inherit.  Instead every event is independent (to force me to provide a full state transition table - better to reduce bugs), and the current character is a class variable of the Transition class.  This simplifies the code.
- Multiple invocations works properly with any boundary.
- There is a branch with a boost::msm version of the implementation (I wanted to give it a go). Turns out, it made things worse in terms of compile time and speed, but I kept it around for my reference.
- Quotes and separations from a set, rather than just one.  This is not auto-detect like you said.  I implemented this because I had it already in my old code.  I templated it on this so users can specialise on just one character (for better performance).
  It didn't complicate the statemachine much, just had to remember what was the quote character used to start the quote process for a particular cell.
- Proper support for \r\n.  The csv standard actually prefers \r\n, and it'll help those poor people who use notepad.exe (or help me when I'm on a PC with nothing else installed).   This did add an extra event and state thus complicating things by a factor.   Note the csv writer now outputs \r\n by default (control by constructor parameter).

Things todo still:
- auto-detect quotes etc (maybe)
- full testing of how \r\n should be done. ie any newlines within a quoted shell also be turned into \r\n
- \ style escaping.
- A few more features that I need, such as

*\* # style commenting

*\* Collapse consecutive separators (I sometimes need to parse files with field separated by a random number of spaces)

*\* Add ability to provide translated error messages (I'll just have a #define wrapper around the error messages for QString::translate to be swapped in).

*\* Clean up the code.  I tried to keep the whitespace changes to a minimum to make it easier to look at diffs, but obviously I'd like to re-tab it etc.   Why do you have // {{{ littered through the code?

I'll be working on it again in about 4 hours from now, and I hope to finish all my changes by end of day today.

**Comment by paulharris** [comment]
Is there any reason why you return true when there is an error?
Why not just throw an exception?

And why do you pass a reference to the buffer pointer?  Just to identify the point of error?

What I have done the past is to keep track of the line and column of the cursor, so that someone with notepad++ or equivalent can to go an exact text location to find the point of the error.

Would that serve your purposes?

**Comment by paulharris** [comment]
Hi again,

I am almost done for now.
I will probably switch to using exceptions unless you have an objection.

I have posted a list of issues on my fork that I'd like to address.
I would dearly love it if someone like yourself could contribute to the further development of this library.
I think this is probably the most complete csv reader for C/C++, which is pretty sad.  Why don't we already have a decent CSV parsing library??   Why must we always "roll your own" ??

No wonder the CSV files out there don't follow any particular standard, since everyone had to write their own parser and writer!

With this library, I hope noone will ever need to roll their own again.

So if you have some time, please contribute, because my time is limited :(
